# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d9a569eef1f36b6e6484c5cc5e328c7131420685d3f7f6d9a71bf0b4ca19021ea90a5f964ffff3505243b1db16daca3b9be77c225b0b3bca8e7cacb858fc1cb

test:
  secret_key_base: ac18c47a07439dc27d84f1206700628b2f5953a3bab7451017c50c6cf697e42c86639c3ee75c6774129e62cfbb1ff6d047fc0878bd6618b5ad00e3b09463163d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
